### ISSUE TITLE
No longer support android ?

### ISSUE THREAD

**Issue by sahalswappo** [pbernasconi/cordova-progressIndicator#26]
It doesn't show in android .

**Comment by bau720123** [comment]
+1
I have the same problem
iOS work perfect but android not

**Comment by sahalswappo** [comment]
@bau720123 actually the other guys create merge request for this fix . I believe it merged in this commit  https://github.com/pbernasconi/cordova-progressIndicator/commit/b5a3fc8a652e63aad23782e47f2d20c1397e0a30

**Comment by bau720123** [comment]
hi @sahalswappo 
thanks for your reply
but I am using PGB (build.phonegap.com)
so...
I wish @pbernasconi or somebody can push a "npm" or "plugins.cordova.io" version
"plugins.cordova.io" is deprecated，choose "npm" is more better

**Comment by pbernasconi** [comment]
Hey guys, I just published this cordova plugin with the latest changes to NPM:

https://www.npmjs.com/package/cordova-plugin-progressindicator

let me know if there are any issues downloading it!
